"""Unit tests for the DocxGenerator service (src/services/docx_generator.py).

The DocxGenerator converts a validated lesson dict into a binary DOCX file.
Tests verify:
1. generate() returns non-empty bytes with DOCX magic bytes.
2. The bytes can be parsed as a valid python-docx Document.
3. The DOCX contains the lesson topic name.
4. The DOCX includes a validation-report appendix when one is supplied.

No database or Claude API calls are made.
"""

from __future__ import annotations

import io

import pytest

from src.services.docx_generator import DocxGenerator
from tests.fixtures.sample_lessons import VALID_GRADE3_LESSON


SAMPLE_VALIDATION_REPORT = {
    "passed": True,
    "checks": [
        {"name": "language_ceiling", "status": "passed", "details": {}},
        {"name": "blooms_distribution", "status": "passed", "details": {}},
        {"name": "interaction_type", "status": "passed", "details": {}},
        {"name": "feedback_structure", "status": "passed", "details": {}},
    ],
    "warnings": [],
    "errors": [],
    "overall_score": 1.0,
}


_TOPIC_NAME = "Trees vs Shrubs"
_CHAPTER_NAME = "Types of Plants"


@pytest.fixture(scope="module")
def generator() -> DocxGenerator:
    """Shared DocxGenerator instance for the whole module."""
    return DocxGenerator()


# ---------------------------------------------------------------------------
# Test 1: generate() returns bytes
# ---------------------------------------------------------------------------


def test_generate_returns_bytes(generator):
    """DocxGenerator.generate must return non-empty bytes starting with 'PK'.

    DOCX is a ZIP archive; the PK magic bytes (0x50 0x4B) confirm the output
    is a valid ZIP-based container and not corrupted or empty.
    """
    result = generator.generate(
        lesson_data=VALID_GRADE3_LESSON,
        grade="3",
        subject="EVS",
        topic_name=_TOPIC_NAME,
        chapter_name=_CHAPTER_NAME,
    )

    assert result is not None, "generate must not return None"
    assert isinstance(result, bytes), (
        f"generate must return bytes, got {type(result).__name__}"
    )
    assert len(result) > 100, (
        "generate must return non-empty bytes (minimum valid DOCX is >100 bytes)"
    )
    assert result[:2] == b"PK", (
        "DOCX output must start with ZIP magic bytes 'PK' (0x50 0x4B)"
    )


# ---------------------------------------------------------------------------
# Test 2: Generated DOCX is parseable by python-docx
# ---------------------------------------------------------------------------


def test_generated_docx_is_parseable(generator):
    """The generated bytes can be opened as a valid python-docx Document.

    python-docx raises an exception if the bytes are not valid Office Open XML.
    Successful parsing proves the generator produces structurally correct DOCX.
    """
    from docx import Document

    result = generator.generate(
        lesson_data=VALID_GRADE3_LESSON,
        grade="3",
        subject="EVS",
        topic_name=_TOPIC_NAME,
        chapter_name=_CHAPTER_NAME,
    )
    doc = Document(io.BytesIO(result))

    non_empty_paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
    assert len(non_empty_paragraphs) > 0, (
        "Generated DOCX must contain at least one non-empty paragraph"
    )


# ---------------------------------------------------------------------------
# Test 3: DOCX contains lesson topic name
# ---------------------------------------------------------------------------


def test_docx_contains_lesson_title(generator):
    """The lesson topic name must appear in the generated DOCX document.

    Architecture Section 4.3.4 specifies a title heading.  The topic name
    'Trees vs Shrubs' must appear in the document text.
    """
    from docx import Document

    result = generator.generate(
        lesson_data=VALID_GRADE3_LESSON,
        grade="3",
        subject="EVS",
        topic_name=_TOPIC_NAME,
        chapter_name=_CHAPTER_NAME,
    )
    doc = Document(io.BytesIO(result))

    full_text = "\n".join(p.text for p in doc.paragraphs)
    assert _TOPIC_NAME in full_text, (
        f"Expected topic name '{_TOPIC_NAME}' to appear in the DOCX. "
        f"Document text preview:\n{full_text[:400]}"
    )


# ---------------------------------------------------------------------------
# Test 4: DOCX includes validation report appendix when provided
# ---------------------------------------------------------------------------


def test_docx_includes_validation_appendix_when_provided(generator):
    """When a validation_report is passed, the DOCX contains an appendix section.

    Architecture Section 4.3.4: 'Include validation report as appendix'.
    The words 'Validation' or 'APPENDIX' must appear in the document.
    """
    from docx import Document

    result = generator.generate(
        lesson_data=VALID_GRADE3_LESSON,
        grade="3",
        subject="EVS",
        topic_name=_TOPIC_NAME,
        chapter_name=_CHAPTER_NAME,
        validation_report=SAMPLE_VALIDATION_REPORT,
    )
    doc = Document(io.BytesIO(result))

    full_text = "\n".join(p.text for p in doc.paragraphs).lower()
    assert "validation" in full_text or "appendix" in full_text, (
        "DOCX must include an 'APPENDIX: Validation Report' section when a "
        f"validation_report is supplied. Document text preview:\n{full_text[:400]}"
    )
